### ISSUE TITLE
Not work on El Capitan

### ISSUE THREAD

**Issue by ghost** [w0lfschild/DarkBoot#25]
after applied darkboot 3.5 on El Capitan, my macbook restart can't boot back to osx. i need use usb bootle for help.

**Comment by kndol** [comment]
I met the same problem.

**Comment by jcr-** [comment]
Same. OS 10.11.2 wouldn't boot after dark boot update. Recovery by Restore disk terminal failed; OS locked the boot.efi file and really, really didn't want to let me unlock and rename it (even with sudo) 

Corrected it by booting from external disk and doing a copy and replace in the Finder (authenticating the replace of a locked file finally worked). I could unlock the file in the Finder momentarily, but it would immediately re-lock. I also couldn't add myself as an owner or user of the file, or otherwise change ownership permissions. I think perhaps 10.11.2 added some new active tricks to try to prevent messing with the boot.efi, beyond SIP/rootless which I have disabled. I guess I'll hold out until I see there has been an update that works around this one.
