### ISSUE TITLE
Mac won't boot 

### ISSUE THREAD

**Issue by SkuIISH** [w0lfschild/DarkBoot#27]
Hi, today i tried the darkboot app on the latest version of el capitan (after i disabled the rootless on the recovery partition).
After i selected the black boot screen and rebooted my mac... Well my mac showed me an empty icon like this 🚫 and since i can't access my os x partition.
I tried to find some help and information but the instructions that i found wasn't clear.
If you can please take some of your time to help find a solution i will be very grateful to you!
I have an old time machine backup of the 10.10.5 version if it can help to retrieve the boot.efi file!
Thanks.

**Comment by RushHour2k5** [comment]
Have you tried booting back into the recovery HD using 'Command + R'. From there you should be able to restore the 'boot_stock.efi' file that was backed up by DarkBoot.

**Comment by SkuIISH** [comment]
Can you please give me the instructions clearly if possible im not comfortable with the terminal

**Comment by SkuIISH** [comment]
Where is the saved version created by darkboot.app ?

**Comment by pierremoreau** [comment]
> Where is the saved version created by darkboot.app ?

From http://w0lfschild.github.io/dboot, it should be `/System/Library/CoreServices/boot.efi.bak`. The list of instructions to restore are the following (taken as well from the previously mentioned website):

```
cd /System/Library/CoreServices
mv ./boot.efi ./boot.efi.bak
mv ./boot_stock.efi ./boot.efi
chmod 644 ./boot.efi
chown root:wheel ./boot.efi
chflags uchg ./boot.efi
reboot
```

**Comment by vertmanx** [comment]
I am running El Capitan and this also happened to me. I did the restore process and it still didn't work. Now I renamed the backup file back to the original and I still couldn't boot. I was about to lose my sh*t because, what else can I do once the backup file is gone and its still broken. I did a ls command in terminal to confirm that the backup file was gone. Luckily, I did some research and ran First Aid from the Disk Utility in Recovery Mode. I ran it about 1-2 times at first and still didn't fix it. But I kept trying other things and nothing. I read somewhere to keep running First Aid until I don't see anymore errors. The system did not find any errors to begin with but I ran First Aid about 4-5 times and then restarted using "Startup Disk" and selected my hard drive. Then, in some miracle, it booted correctly!! I rebooted and re-enabled Rootless and I'm not touching DarkBoot until he works out the kinks for El Capitan. I would mark this program in Alpha stage because it's not perfect for El Capitan. You need to fix some of these issues. I warn people, DO NOT run this on El Capitan unless you make a total backup that you can revert back to. Such a simple program can destroy your entire machine. It's not worth the risk. Please correct this for El Capitan. 

Thank you.
