### ISSUE TITLE
Boot Image not working with FileVault

### ISSUE THREAD

**Issue by digitol** [w0lfschild/DarkBoot#45]
Will Darkboot work with FileVault enabled? It appears to custom background color works, however custom logo is not working. Could this be because part of the boot image is read from the HD, and it can't get access to it during startup due to encryption/time to unlock? Thanks for this wonderful awesome utility!! 👍

**Comment by w0lfschild** [comment]
That could certainly be the case. I've never used filevault.

**Comment by dabrain13** [comment]
Custom color will work regardless of HD setup because it's loaded from NVRAM (which resides on a special chip in your computer). Your HD being encrypted doesn't affect it at all.

BootXChanger (which this app uses) sets the boot image by setting a path in bootloader settings instead of altering the actual bootloader. So I think your guess is correct. The bootloader can't access the appropriate file and defaults.

I seem to recall that when you enable FileVault, the OS puts the necessary boot code on the Recovery partition, so in theory, you could replace the image there and get a custom boot image, even with file vault.

**Comment by sidpagariya** [comment]
Um, after updating to the latest DarkBoot, my custom Logo does not work on the same beta -- macOS Sierra beta 6

**Comment by sidpagariya** [comment]
Probably an issue with the latest update?

**Comment by ardacebi** [comment]
No it will not work when FileVault is enabled on your Mac.
