### ISSUE TITLE
Dark Boot Won't Go Back to Default

### ISSUE THREAD

**Issue by brianfos** [w0lfschild/DarkBoot#79]
I'm using DarkBook 5.2.0 under Sierra 10.12.6. I was able to make it go into a Black boot color, but it refuses to go back to gray or "Default" when I select that option even though the DarkBoot window says that it "Applied" the changes. Yet, when I actually restart, my Mac still boots in black. How do I get the Default back?

**Comment by brianfos** [comment]
I think I resolved the problem I just cited above. I found the file named "com.dabrain13.darkboot.plist" and trashed it. When I rebooted, my Mac loaded with a default gray desktop!

**Comment by wwwonka** [comment]
Hey, thanks for giving us the exact name of the baddy. Would you care to tell us the exact path at which "com.dabrain13.darkboot.plist" is located in the Finder so that we can trash it as well? Thank you.

EDIT: 
An simmilar issue had the answer ; so, as mentioned here: https://github.com/w0lfschild/DarkBoot/issues/73 . You have to delete the .plist which is located in "/Library/LaunchDaemons/" and reboot twice after in order for your action to take effect.  Future readers, be careful : during the process,  I stumbled on a "com.dabrain13.darkboot.plist" file in the DarkBoot.app internal structure, this isnt the right file even if it has the exact same name, make sure you go in the "Library", as mentionned above.  Goodbyye!

**Comment by w0lfschild** [comment]
Hopefully this is fixed in 6.0.1
